<?php

namespace App\Http\Constants;


/***
 *	Class CErrCodeModelDataHub
 *	@package App\Http\Constants
 */
class CErrCodeModelDataHub extends CErrCode
{
	//
	//	app/Http/Models/DataHub/CDataHubTaskOrder.php
	//	 2000 --- 2999
	//
	const CDATAHUBTASKORDER_ERROR_SAVETASKORDER_PARAM					= self::ERROR_MODEL_DATAHUB_START + 2000;
	const CDATAHUBTASKORDER_ERROR_SAVETASKORDER_PARAM_EDITOR_LIST				= self::ERROR_MODEL_DATAHUB_START + 2001;
	const CDATAHUBTASKORDER_ERROR_SAVETASKORDER_FAILED					= self::ERROR_MODEL_DATAHUB_START + 2020;
	const CDATAHUBTASKORDER_ERROR_SAVETASKORDER_INVALID_EDITOR_LIST				= self::ERROR_MODEL_DATAHUB_START + 2030;
	const CDATAHUBTASKORDER_ERROR_SAVETASKORDER_EMPTY_EDITOR_LIST				= self::ERROR_MODEL_DATAHUB_START + 2031;


	

}